### ISSUE TITLE
Import Error: No module named Player

### ISSUE THREAD

**Issue by JStiggy** [Rensselaer-AI-League/GeneralizedGameServer#1]
```
C:\Users\steigj3\Documents\GeneralizedGameServer>python -m host.run rps
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\steigj3\Documents\GeneralizedGameServer\host\run.py", line 4, i
n <module>
    from server import *
  File "host\server.py", line 35, in <module>
    import player.Player
ImportError: No module named Player

C:\Users\steigj3\Documents\GeneralizedGameServer>pause
Press any key to continue . . .
```

**Comment by ZishanHuang** [comment]
Change line 35 to:

`from player import Player`
